### ISSUE TITLE
Add font-weight design tokens

### ISSUE THREAD

**Issue by jrschumacher** [virtru/virtuoso-design-system#83]
It would be helpful if there were font-weight design tokens:

```
--vds-font-weight-normal
--vds-font-weight-thick
--vds-font-weight-thicker
```

**Comment by avkvirtru** [comment]
@virtruvee to say which 3 styles we're currently using in design 🎨

**Comment by avkvirtru** [comment]
I started a font weight audit in Abstract for @virtruvee to review here https://share.goabstract.com/43d0e445-2b83-4c74-b57d-178621f44383

So far looks like these are the fonts in heavy use:

1. OpenSans-Regular (Atoms, Molecules, Organisms)
2. OpenSans-Bold (Atoms, Molecules, Organisms)
3. Raleway-Bold (Atoms, Molecules, Organisms)
4. OpenSans-Semibold (Organisms)
5. Raleway-Semibold (Organisms)

Which translates to the following font weights in code:
1. regular - OpenSans only
1. semibold - OpenSans & Raleway
1. bold - OpenSans & Raleway

The good news is, this also means we can safely delete many unused variants of Open Sans and Raleway and ship a smaller binary ;) will leave that for a follow-up issue…

@jrschumacher lmk if you're good with the second list of 3 font weights above
